### ISSUE TITLE
编译报错：Property without attribute 'copy' was selected for synthesis

### ISSUE THREAD

**Issue by KaraRyougi** [fuzhuo/DanMuPlayer#5]
尝试编译使用了本播放器的[该项目](https://github.com/xioxin/biliATV)。编译时有如下报错：
``.../biliATV/DanMuPlayer/DanMuPlayer/DMPlaylist.h:22:33: Property without attribute 'copy' was selected for synthesis``

错误是出现在
```@property (nonatomic) NSString *description;```

萌新并不懂斯威夫特……求助orz……

**Comment by KaraRyougi** [comment]
把
``@property (nonatomic) NSString *description;``
瞎改成
``@property (nonatomic, copy) NSString *description;``
就不报错了……

**Comment by qiudaomao** [comment]
好像有copy...
