### ISSUE TITLE
I can't build ijkplayer for this project

### ISSUE THREAD

**Issue by florino** [fuzhuo/DanMuPlayer#7]
The one linked from this project returns a openssl error when building. I also found a tvos port but that does not build either
https://github.com/qiudaomao/ijkplayer/tree/tvos

Even if this is a few months old, it seems it uses a different ijkplayer. There are no ios-init.sh and build-openssl.sh in neither branches of ijkplayer that I found.

Could you point me to the right ijkplayer branch? Thank you

**Comment by qiudaomao** [comment]
Sorry, seems some typo in README.md
You can follow below step

```shell
git clone git@github.com:qiudaomao/DanMuPlayer.git
cd DanMuPlayer
git submodule update --init --recursive
cd ijkplayer
./init-ios-openssl.sh
cd ios
./compile-openssl.sh
./compile-ffmpeg.sh

You should get everything you need
```
