### ISSUE TITLE
音频Airplay到homepod会有延迟吗？

### ISSUE THREAD

**Issue by CoderTonyChan** [fuzhuo/DanMuPlayer#8]
音频Airplay到homepod会有延迟吗？

**Comment by RunzhouLi** [comment]
Safari以外的音频全部都有延迟，Safari的控制命令（暂停/播放）有延迟

**Comment by qiudaomao** [comment]
HomePod的AirPlay音频有固定延迟2秒。
播放视频时视频轨延迟两秒来匹配音频就行了，你需要的结果是音视频同步而不是解决掉延迟。Apple内置的AVPlayer自动适配

iOS/tvOS的API可以拿到当前输出音频的Latency，这样自动适配就可以了
`objc
[AVAudioSession.sharedInstance outputLatency]
`
